#!/usr/bin/env python3

from __future__ import annotations

import argparse
from pathlib import Path

def render(root: Path, source_dir: Path) -> str:
    sources = sorted(
        (
            path
            for path in source_dir.iterdir()
            if path.is_file() and path.suffix.lower() in {".c", ".cpp"}
        ),
        key=lambda path: path.name,
    )
    if not sources:
        raise ValueError(f"no generated C/C++ sources found in {source_dir}")

    relative_sources = [path.relative_to(root).as_posix() for path in sources]
    lines = [
        "# Generated by tools/write_generated_manifest.py; do not edit.",
        "set(TWINE_GENERATED_CPU_SOURCES",
        *(f'    "${{CMAKE_SOURCE_DIR}}/{path}"' for path in relative_sources),
        ")",
        "",
    ]
    return "\n".join(lines)

def main() -> int:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source-dir",
        type=Path,
        default=root / "build" / "generated" / "RecompiledFuncs",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=root / "build" / "generated" / "generated_sources.cmake",
    )
    args = parser.parse_args()

    source_dir = args.source_dir.resolve()
    output = args.output.resolve()
    root = root.resolve()
    if root not in source_dir.parents or root not in output.parents:
        raise ValueError("generated paths must stay inside the project")

    content = render(root, source_dir)
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_suffix(output.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8", newline="\n")
    temporary.replace(output)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
