function(twine_windows_manifest target use_utf8_arguments)
    if(NOT MSVC)
        return()
    endif()
    set(TWINE_MANIFEST_FILES "")
    set(TWINE_MANIFEST_CODEPAGE "")
    if(use_utf8_arguments)
        set(TWINE_MANIFEST_CODEPAGE "    <activeCodePage xmlns=\"http://schemas.microsoft.com/SMI/2019/WindowsSettings\">UTF-8</activeCodePage>")
    endif()
    set(names "")
    foreach(dll IN LISTS ARGN)
        get_filename_component(name "${dll}" NAME)
        if(NOT name MATCHES "^[A-Za-z0-9_.-]+\\.dll$")
            message(FATAL_ERROR "Invalid app-local DLL name: ${name}")
        endif()
        list(APPEND names "${name}")
    endforeach()
    list(REMOVE_DUPLICATES names)
    list(SORT names)
    foreach(name IN LISTS names)
        string(APPEND TWINE_MANIFEST_FILES "  <file name=\"${name}\"/>\n")
    endforeach()
    set(TWINE_MANIFEST_ID "TWINE.${target}")
    set(manifest "${CMAKE_BINARY_DIR}/manifests/${target}.manifest")
    configure_file("${CMAKE_SOURCE_DIR}/packaging/windows/runtime.manifest.in" "${manifest}" @ONLY)
    target_link_options(${target} PRIVATE "/MANIFEST:EMBED" "/MANIFESTINPUT:${manifest}")
    set_property(TARGET ${target} APPEND PROPERTY LINK_DEPENDS "${manifest}")
endfunction()
